name: device-checkout
version: '0.2.1'
summary: A web-based device registry for managing test gear
description: |
  A web service for managing shared test gear. You can register devices, give
  them a url, and then people can check out and reserve devices.

grade: stable
confinement: strict

parts:
  device-checkout:
    source: https://github.com/tismith/device-checkout-rs.git
    plugin: x-rust
    rust-revision: nightly-2018-06-05
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/var/lib/device-checkout
      cp -r templates ${SNAPCRAFT_PART_INSTALL}/var/lib/device-checkout
    build-packages:
      - build-essential
      - libsqlite3-dev
    stage-packages:
      - libsqlite3-0

apps:
  device-checkout:
    plugs:
      - network-bind
    command: bin/device-checkout --templates $SNAP/var/lib/device-checkout/templates --database $SNAP_DATA/devices.db
    daemon: simple
    restart-condition: always
